import type { Metadata } from 'next'
import { Exo_2, Montserrat } from 'next/font/google'

import { Footer, Header, PopUpFormButtonFixed } from '@/components'

import './globals.css'

const montserrat = Montserrat({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const exo = Exo_2({
  weight: ['700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-exo',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="uk-UA"
      className={`${montserrat.variable} ${exo.variable} bg-coal-800`}
    >
      <body>
        <div className="min-h-screen flex flex-col justify-between">
          <div>
            <Header />
            <div>{children}</div>
          </div>
          <Footer />
          <PopUpFormButtonFixed />
        </div>
      </body>
    </html>
  )
}
