import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header, Footer, PopUpForm } from '../components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-coal-800 min-h-screen flex flex-col justify-between">
          <div>
            <Header />
            <div>{children}</div>
          </div>
          <Footer />
          <PopUpForm />
        </div>
      </body>
    </html>
  )
}
