import type { Metadata } from 'next'
import { Montserrat, Exo_2 } from 'next/font/google'
import './globals.css'
import { Header, Footer, PopUpFormButtonFixed } from '../components'

const montserrat = Montserrat({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const exo = Exo_2({
  weight: ['700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-exo',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.variable} ${exo.variable} bg-coal-800`}>
      <body>
        <div className="bg-coal-800 min-h-screen flex flex-col justify-between">
          <div>
            <Header />
            <div>{children}</div>
          </div>
          <Footer />
          <PopUpFormButtonFixed />
        </div>
      </body>
    </html>
  )
}
