name: CI/CD Workflow
on:
  push:
    branches:
      - feature/docker-compose

env:
  SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
  SERVER_PUBLIC_KEY: ${{ secrets.SERVER_PUBLIC_KEY }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash deploy.sh
