name: CI/CD Workflow
on:
  push:
    branches:
      - feature/docker-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: bash deploy.sh
    
