name: CI/CD Workflow
on:
  push:
    branches:
      - feature/docker-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /srv/next-app
            git pull origin feature/docker-compose
            git checkout feature/docker-compose
            docker compose build --no-cache next-app
            docker compose down next-app
            docker compose up -d next-app
            docker system prune -af
     