name: CI/CD Workflow
on:
  push:
    branches:
      - feature/docker-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env: 
          SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
        run: |
          echo ${{secrets.SERVER_HOSTNAME}} | sed 's/./& /g' 
      - run: bash deploy.sh
    
