name: CI/CD Workflow
on:
  push:
    branches:
      - feature/docker-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env: 
            SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
            SERVER_PUBLIC_KEY: ${{ secrets.SERVER_PUBLIC_KEY }}
        run: bash deploy.sh
    
