name: CI/CD Workflow
on:
  push:
    branches:
      - feature/docker-compose

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
    steps:
      - uses: actions/checkout@v3
      - run: bash deploy.sh
