name: CI/CD Workflow
on:
  push:
    branches:
      - feature/docker-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SERVER_HOSTNAME }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SERVER_HOSTNAME}} | sed 's/./& /g' 
      # - uses: actions/checkout@v3
      # - shell: bash
      #   env: 
      #     SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
      #   run: |
      #     echo ${{secrets.SERVER_HOSTNAME}} | sed 's/./& /g' 
      # - run: bash deploy.sh
    
